#server.servlet.context-path=/

spring:
  jpa:
    hibernate: 
      ddl-auto: create,update
    generate-ddl: true
    database: mysql
    show-sql: true
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        hbm2ddl: 
          auto: none

  autoconfigure: 
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  
  datasource: 
    hikari: 
      jdbc-url: jdbc:mysql://127.0.0.1:3306/studydb?verifyServerCertificate=false&useSSL=false
      username: root
      password: skbaek1234
      driver-class-name: com.mysql.jdbc.Driver
      max-lifetime: 5000
      idle-timeout: 5000
